name: Unit Tests
on: [push, pull_request]

jobs:
  build:
    name: Test my project
    runs-on: ubuntu-latest
    container: unityci/editor:6000.0.23f1-linux-il2cpp-3.1.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: UnityProject/Library
          key: Library-test-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-test-

      - name: Create ULF license file
        env:
          ULF_CONTENT: ${{ secrets.UNITY_LICENSE }}
        run: echo "$ULF_CONTENT" > /tmp/license.ulf

      - name: Activate Unity License
        env:
          ULF_CONTENT: ${{ secrets.UNITY_LICENSE }}
        run: |
          unity-editor -nographics -batchmode -manualLicenseFile /tmp/license.ulf -logfile

      - name: Generate Solution
        run: |
          unity-editor -nographics -projectPath ./UnityProject -executeMethod Packages.Rider.Editor.RiderScriptEditor.SyncSolution -quit
      
      - name: Return Unity License
        env:
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        continue-on-error: true
        run: unity-editor -quit -batchmode -returnlicense -username "$UNITY_EMAIL" -password "$UNITY_PASSWORD"

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      
      - name: Run Tests
        run: dotnet test MyGameTests