name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    name: Test my project
    runs-on: ubuntu-latest
    env:
      UNITY_PROJECT_DIR: "UnityProject" 
      # UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      # UNITY_SERIAL: ${{ secrets.UNITY_LICENSE }}
      # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_LICENSE }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ env.UNITY_PROJECT_DIR }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}