name: Unit Tests
on: [push, pull_request]

jobs:
  build:
    name: Test my project
    runs-on: ubuntu-latest
    container: unityci/editor:6000.0.23f1-linux-il2cpp-3.1.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log Unity Serial
        run: |
          echo "Unity Serial: ${{ secrets.UNITY_SERIAL }}"
          
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: ./UnityProject/Library
          key: Library-test-${{ hashFiles('./UnityProject/Assets/**', './UnityProject/Packages/**', './UnityProject/ProjectSettings/**') }}
          restore-keys: Library-test-

      - name: Activate Unity License
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        run: |
          unity-editor -logFile /dev/stdout -quit \
            -username "$UNITY_EMAIL" \
            -password "$UNITY_PASSWORD" \
            -serial "$UNITY_SERIAL" \
            -projectPath ./UnityProject

      - name: Generate Solution
        run: |
          unity-editor -nographics \
            -projectPath ./UnityProject \
            -executeMethod Packages.Rider.Editor.RiderScriptEditor.SyncSolution \
            -quit

      - name: Return Unity License
        continue-on-error: true
        run: unity-editor -quit -returnlicense \
          -logFile /dev/stdout \
          -username "$UNITY_EMAIL" \
          -password "$UNITY_PASSWORD"
          -projectPath ./UnityProject

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Run Tests
        run: dotnet test MyGameTests